### ISSUE TITLE
raw-h2: connection pool design

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aapns#23]
#### Background

@ojii and I have 2 use cases for `aapns`:
* batch app badge update (latency is not important; throughput could be, but weirdly is quite small)
* real-time actionable notification (latency is key)

I've tested 1 connection using the new `raw-h2` branch against apple's development server. Here are the results from my home:

* start python, establish 1 connection, send a few notifications, close connections, quit: `0.83s`
* same as above, `+100` requests: `0.98s`, thus 𝚫 is `0.15s / 100 req`
* latency for first few requests: `0.12s`
* `+100`, latency for last few requests: `0.36s`

Apple allows up to `1000` concurrent requests per connection, but I can't test that because above `~400` requests to the same device, I start getting `429` status code back 😓. The latency in that case jumps to `~1.2s`.

The results could be skewed by my having only 1 device and thus testing with 1 device token. It's possible that Apple server serialises requests per device. Apple responds much faster when token is bogus, typically `~0.54s` for me.

#### Specifications

1. simple use case - few notifications now and then
2. batch use case - throughput over latency
3. real-time use case - latency trumps all

I'm thinking following connection [pool] design for these cases:

#### Simple, connection on demand

* initialise and enter context, nothing created yet
* on first request create a connection (this makes 1st request slow)
* connection is kept around
* subsequent requests reuse the connection and are fast
* eventually connection dies (today that means pending requests error out)
* on next request, create a new connection
* exit context, connection, if any, is closed

#### Batch use case

* initialise and enter context, that creates N connections (perhaps N=1)
* requests are assigned to connections round-robin
* a connection may be blocked (has 1000 concurrent requests), then another is used
* when connections die, they are replaced in the background
* exit the context, all connections are closed

#### Real-time use case

* initialise and enter context, that creates N connections (N>=2, ideally largish N)
* requests are assigned to connections weighted round-robin
* a connection does not allow more than e.g. 10 concurrent requests
* if a connection is busy, another is used
* [perhaps] there should be a skew to round-robin mechanism, i.e. small preference for older connections, lest perfect round-robin allocation result in simultaneous exhaustion of all connections, resulting in latency spike when all connections are to be replaced at the same time
* [perhaps] alternatively, connections are retired well before they are exhausted
* when connections die they are replaced in the background
* exit the context, all connections are closed

**Comment by takehikokodama** [comment]
> * exit the context, all connections are closed

In Real-time use case, when or how often does it happen?

**Comment by dimaqq** [comment]
@ojii indicated that he'd start the connection pool at the start of the server.
It may only be closed when the server is shutting down.
(in other words, basically never)

I figure that's a common use-case for the cloud.

**Comment by ojii** [comment]
> * initialise and enter context, that creates N connections (perhaps N=1)

Did you check if APNS will just close idle connections if they're opened but then for a while no request is made?

**Comment by ojii** [comment]
> * a connection does not allow more than e.g. 10 concurrent requests

why?

**Comment by dimaqq** [comment]
> > * a connection does not allow more than e.g. 10 concurrent requests
> 
> why? as in, why not use the max concurrency as advertised by the server

To ensure low latency;
Somehow latency is proportional to how "busy" a connection is.

**Comment by michaelaw320** [comment]
As far as I can see the latency difference between them are not that significant (less than 1s) the biggest latency would be from APN Server - Mobile Device itself, which can take seconds more.

I'd be in favour of N>=2 + Many streams like the Batch-use case for general use

**Comment by dimaqq** [comment]
> > * initialise and enter context, that creates N connections (perhaps N=1)
> 
> Did you check if APNS will just close idle connections if they're opened but then for a while no request is made?

I've tested exponentially increasing delays between requests.
(so a connection has had a successful request, and now there's a long gap).
a 1024s idle period does not kill the connection.

I'll test a fresh unused connection being idle next.

**Comment by ojii** [comment]
IMHO the priorities should be:

1. Stability (doesn't crash weirdly all the time).
2. Throughput (doesn't crash under load and can send tons of notifications if needed).
3. Latency (this library is such a small part of the overall latency that optimizing this last seems reasonable).

So I'd  prefer a simple design (eg no background refresh because that seems like a prime source of trouble) sacrificing some performance if needed. If/once we have an actual reliable h2 client (which this library sadly never had) we can worry about latency etc.

**Comment by dimaqq** [comment]
re: ↑ what throughput are you thinking of? how many requests per second?

**Comment by ojii** [comment]
> re: ↑ what throughput are you thinking of? how many requests per second?

that's really hard to answer. "as much as possible"/"it depends"? we never benchmarked the v1 (my custom terrible h2 client) or v2 (httpx) so I have no baseline, and as you learned, getting good numbers is almost impossible because you need lots of real devices (with a push-enabled app installed) to do much.

**Comment by dimaqq** [comment]
Thank you all for your input.
I've settled on naive connection pool for now.
Hopefully the pros are:
* stability
* durability in face of network errors
* throughput
* [kinda] latency, by overprovisioning pool size
For cons, I'll open new tickets.
